[package]
name = "boids"
version = "0.1.0"
authors = ["nika"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15"
rand="*"
nannou_osc = "0.1.0"